### ISSUE TITLE
Local Development of Theme

### ISSUE THREAD

**Issue by mansona** [TryGhost/Starter#1]
Howdy folks 👋 

In the [Development section of the readme](https://github.com/TryGhost/Starter#development) it says that you can run: 

```bash
$ yarn install
$ yarn dev
```

and editing the CSS will automatically update the assets. But is it possible to actually see what this is supposed to look like anywhere? I was half expecting a local server that would show the template while I was working on it 🤔 Also this starter theme doesn't have a demo URL like the other themes that were released in January.

**Comment by kevinansfield** [comment]
@mansona you would need to have the theme installed in Ghost https://docs.ghost.org/install/local/ to be able to see changes, theme's aren't standalone in a way that they can have their own local server. 

The `yarn dev` command only watches for changes to CSS files so that it can re-build them - each Ghost theme can optionally have a build pipeline for assets.

**Comment by mansona** [comment]
Ok so the reason I was asking was because when I finished my thing it all came out looking a bit strange, but now that I've tested Starter in actual ghost it looks like it's supposed to be like this to start off with 😂 

![Screenshot 2019-03-27 at 20 17 08](https://user-images.githubusercontent.com/594890/55109320-743a3400-50cd-11e9-9136-d9f33b0bfdf9.png)

thanks for answering my questions 🎉
